<?php
/*
 * settings.php
 *
 * Settings page for the AbuseIPDB Suricata Watcher package. Values are
 * stored in config.xml (installedpackages/pfsense_abuseipdb/settings) and
 * generated into the package ini on save, then the service is restarted.
 * Secrets are never entered here: the *_file keys point at credential
 * files under /root/.credentials/.
 */
require_once("guiconfig.inc");

$ini_file = '/usr/local/pfsense_abuseipdb/etc/pfsense_abuseipdb.ini';
$rcd = '/usr/local/etc/rc.d/pfsense_abuseipdb';

/* key => array(label, type, help) */
$fields = array(
    /* Suricata */
    'alerts_file' => array('Suricata eve.json path', 'text', 'Path to the eve.json alert log.'),
    'block_log_file' => array('Block log path', 'text', 'Per-IP detection log that drives the reporting threshold.'),
    'wan' => array('WAN interface', 'text', 'Interface name, e.g. igb0.'),
    /* AbuseIPDB */
    'abuseipdb_token_file' => array('AbuseIPDB token file', 'text', 'Path to the AbuseIPDB API token.'),
    'abuseipdb_user_id' => array('AbuseIPDB user id', 'text', 'Your AbuseIPDB account id.'),
    'report_limit' => array('Report limit', 'number', 'Detections in the block log required before an IP is reported.'),
    'abuseipdb_confidense_score_limit' => array('Confidence score limit', 'number', 'AbuseIPDB confidence score required to file a report (past 90 days).'),
    /* Mysql */
    'use_mysql' => array('Use MySQL', 'select', 'Log every report to MySQL.'),
    'domain' => array('Domain', 'text', 'Local domain used in reports.'),
    'mysql_host' => array('MySQL host', 'text', ''),
    'mysql_user' => array('MySQL user', 'text', ''),
    'mysql_password_file' => array('MySQL password file', 'text', 'Path to the database password file.'),
    'mysql_database' => array('MySQL database', 'text', ''),
    /* ipinfo */
    'ipinfo_token_file' => array('ipinfo token file', 'text', ''),
    'show_ip_info' => array('Show IP info', 'select', 'GeoIP lookup for each alert.'),
    'show_ip_abusedb_email' => array('Show abuse contact', 'select', 'WHOIS abuse-mailbox lookup for each alert.'),
    /* Email */
    'send_abuse_email_report' => array('Send abuse email', 'select', 'Email the WHOIS abuse contact.'),
    'email_report_limit' => array('Email report limit', 'number', 'Detections required before an abuse email is sent.'),
    'report_name' => array('Report name', 'text', 'Display name of the email sender.'),
    'report_email' => array('Report email', 'text', 'From address for abuse emails.'),
    'abuseip_email_password_file' => array('Abuse email password file', 'text', 'Path to the SMTP password file.'),
    'report_smtp_host' => array('SMTP host', 'text', ''),
    'report_smtp_port' => array('SMTP port', 'number', ''),
    /* X-ARF */
    'send_xarf_report' => array('Send X-ARF reports', 'select', 'Report to abusix via X-ARF.'),
    'xarf_token_file' => array('X-ARF token file', 'text', 'Path to the Abusix API key file.'),
    'xarf_org' => array('X-ARF org', 'text', ''),
    'xarf_contact' => array('X-ARF contact', 'text', 'Abuse contact address sent with X-ARF reports.'),
    'xarf_domain' => array('X-ARF domain', 'text', ''),
    /* Whitelists + misc */
    'suricata_whitelists' => array('Whitelist pf tables', 'text', 'Comma-separated pf table names used to whitelist source IPs.'),
    'pfsense_token_file' => array('pfSense API token file', 'text', 'Used by the (optional) filterlog section.'),
    'pfsense_url' => array('pfSense API URL', 'text', ''),
    'gmail_app_password_file' => array('Gmail app password file', 'text', 'Reserved for future use.')
);

/* Yes/no toggles render as selects. */
$yesno_keys = array();
foreach ($fields as $key => $f) {
    if ($f[1] == 'select') {
        $yesno_keys[] = $key;
    }
}

function pfsense_abuseipdb_read_ini($file, $keys) {
    $vals = array();
    if (file_exists($file)) {
        foreach (file($file, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) as $line) {
            if (preg_match('/^([a-z_]+)=(.*)$/', $line, $m) && isset($keys[$m[1]])) {
                $vals[$m[1]] = $m[2];
            }
        }
    }
    return $vals;
}

function pfsense_abuseipdb_gen_ini($v) {
    return "; pfsense_abuseipdb.ini - generated by the pfSense package settings page\n" .
        "pfsense_token_file={$v['pfsense_token_file']}\n" .
        "abuseipdb_token_file={$v['abuseipdb_token_file']}\n" .
        "ipinfo_token_file={$v['ipinfo_token_file']}\n" .
        "gmail_app_password_file={$v['gmail_app_password_file']}\n" .
        "mysql_password_file={$v['mysql_password_file']}\n" .
        "abuseip_email_password_file={$v['abuseip_email_password_file']}\n" .
        "xarf_token_file={$v['xarf_token_file']}\n" .
        "pfsense_url={$v['pfsense_url']}\n" .
        "alerts_file={$v['alerts_file']}\n" .
        "block_log_file={$v['block_log_file']}\n" .
        "wan={$v['wan']}\n" .
        "abuseipdb_user_id={$v['abuseipdb_user_id']}\n" .
        "report_limit={$v['report_limit']}\n" .
        "abuseipdb_confidense_score_limit={$v['abuseipdb_confidense_score_limit']}\n" .
        "domain={$v['domain']}\n" .
        "mysql_host={$v['mysql_host']}\n" .
        "mysql_user={$v['mysql_user']}\n" .
        "mysql_database={$v['mysql_database']}\n" .
        "use_mysql={$v['use_mysql']}\n" .
        "show_ip_info={$v['show_ip_info']}\n" .
        "show_ip_abusedb_email={$v['show_ip_abusedb_email']}\n" .
        "send_abuse_email_report={$v['send_abuse_email_report']}\n" .
        "email_report_limit={$v['email_report_limit']}\n" .
        "report_name={$v['report_name']}\n" .
        "report_email={$v['report_email']}\n" .
        "report_smtp_host={$v['report_smtp_host']}\n" .
        "report_smtp_port={$v['report_smtp_port']}\n" .
        "send_xarf_report={$v['send_xarf_report']}\n" .
        "xarf_org={$v['xarf_org']}\n" .
        "xarf_contact={$v['xarf_contact']}\n" .
        "xarf_domain={$v['xarf_domain']}\n" .
        "suricata_whitelists={$v['suricata_whitelists']}\n";
}

/* Initial values: config.xml settings first, then the live ini as fallback. */
$vals = array();
foreach ($fields as $key => $f) {
    $vals[$key] = config_get_path("installedpackages/pfsense_abuseipdb/settings/{$key}");
    if ($vals[$key] === null) {
        $vals[$key] = '';
    }
}
$ini_vals = pfsense_abuseipdb_read_ini($ini_file, $fields);
foreach ($fields as $key => $f) {
    if ($vals[$key] === '' && isset($ini_vals[$key])) {
        $vals[$key] = $ini_vals[$key];
    }
}

$input_errors = array();
$saved = false;

if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    $new = array();
    foreach ($fields as $key => $f) {
        $val = trim($_POST[$key] ?? '');
        $val = str_replace(array("\r", "\n", "\0"), '', $val);
        if ($f[1] == 'select' && !in_array($val, array('yes', 'no'))) {
            $val = 'no';
        }
        if ($f[1] == 'number' && $val !== '' && !ctype_digit($val)) {
            $input_errors[] = sprintf(gettext('%s must be a number.'), $f[0]);
        }
        $new[$key] = $val;
    }
    foreach (array('alerts_file', 'block_log_file', 'wan') as $req) {
        if ($new[$req] === '') {
            $input_errors[] = sprintf(gettext('%s is required.'), $fields[$req][0]);
        }
    }
    if (empty($input_errors)) {
        foreach ($yesno_keys as $key) {
            if ($new[$key] === '') {
                $new[$key] = 'no';
            }
        }
        config_set_path('installedpackages/pfsense_abuseipdb/settings', $new);
        write_config("AbuseIPDB package settings updated");
        file_put_contents($ini_file, pfsense_abuseipdb_gen_ini($new));
        chmod($ini_file, 0644);
        mwexec_bg("/usr/local/etc/rc.d/pfsense_abuseipdb restart");
        $saved = true;
        $vals = $new;
    }
}

$pgtitle = array(gettext("Services"), gettext("AbuseIPDB"), gettext("Settings"));
include("head.inc");

$tab_array = array();
$tab_array[] = array(gettext("Status"), false, "/packages/pfsense_abuseipdb/status.php");
$tab_array[] = array(gettext("Settings"), true, "/packages/pfsense_abuseipdb/settings.php");
display_top_tabs($tab_array);

if ($saved) {
    print_info_box(gettext('Settings saved, ini regenerated and the watcher service was restarted.'), 'success');
}
if (!empty($input_errors)) {
    print_input_errors($input_errors);
}
?>

<form action="settings.php" method="post">
	<div class="panel panel-default">
		<div class="panel-heading"><h2 class="panel-title"><?= gettext('AbuseIPDB Suricata Watcher settings') ?></h2></div>
		<div class="panel-body">
			<div class="table-responsive">
				<table class="table table-striped table-hover">
					<tbody>
<?php foreach ($fields as $key => $f): ?>
						<tr>
							<td style="width: 30%;">
								<strong><?= htmlspecialchars($f[0]) ?></strong><br />
								<code><?= htmlspecialchars($key) ?></code>
							</td>
							<td>
<?php if ($f[1] == 'select'): ?>
								<select class="form-control" name="<?= htmlspecialchars($key) ?>">
									<option value="yes" <?= ($vals[$key] == 'yes') ? 'selected' : '' ?>><?= gettext('yes') ?></option>
									<option value="no" <?= ($vals[$key] != 'yes') ? 'selected' : '' ?>><?= gettext('no') ?></option>
								</select>
<?php else: ?>
								<input class="form-control" type="text" name="<?= htmlspecialchars($key) ?>" value="<?= htmlspecialchars($vals[$key]) ?>" autocomplete="off" />
<?php endif ?>
<?php if (!empty($f[2])): ?>
								<span class="help-block"><?= htmlspecialchars($f[2]) ?></span>
<?php endif ?>
							</td>
						</tr>
<?php endforeach ?>
					</tbody>
				</table>
			</div>
		</div>
		<div class="panel-footer">
			<button type="submit" class="btn btn-primary" name="save" value="save">
				<i class="fa fa-save icon-embed-btn"></i><?= gettext('Save and restart watcher') ?>
			</button>
			<span class="help-block">
				<?= gettext('Credential fields hold file paths only - the actual secrets stay in the files under /root/.credentials/.') ?>
			</span>
		</div>
	</div>
</form>

<?php include("foot.inc");
